Code/MasterDM/UI/VFS.UI.MasterDM/Controllers/CountriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using VFS.Common.Models.Masters;
using VFS.Data.EFCore.Common;

namespace VFS.UI.MasterDM.Controllers
{
    public class CountriesController : Controller
    {
        private readonly ApplicationContext _context;       

        public CountriesController(ApplicationContext context)
        {
            _context = context;
        }

        // GET: Countries
        public async Task<IActionResult> Index(int? id,string Search)
        {
            if (Search == null) Search = string.Empty;
            //var _DBMISSIONContext = _context.Country.Where(a => a.Name == Search).Include(c => c.CreatedByNavigation);
            if(id != null)
            {
                if (id != 3)
                {
                    HttpContext.Session.SetInt32("IsEditable", 1);
                }
                else
                {
                    HttpContext.Session.SetInt32("IsEditable", 0);
                }
                ViewData["IsEditable"] = HttpContext.Session.GetInt32("IsEditable");
                HttpContext.Session.SetInt32("UserId", Convert.ToInt32(id));
            }
            if(Search != string.Empty)
            {
                return View(await _context.Country.Where(a => a.Name.Contains(Search) || a.Isocode2.Contains(Search) || a.Isocode3.Contains(Search) || a.Nationality.Contains(Search)).Include(c => c.CreatedByNavigation).ToListAsync());
            }
            else
            {
                return View(await _context.Country.Include(c => c.CreatedByNavigation).ToListAsync());
            }           

        }

        // GET: Countries/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var country = await _context.Country
                .FirstOrDefaultAsync(m => m.Id == id);
            if (country == null)
            {
                return NotFound();
            }

            return View(country);
        }

        // GET: Countries/Create
        public IActionResult Create()
        {
            ViewData["CreatedBy"] = new SelectList(_context.UserMaster, "Id", "FirstName");
            return View();
        }

        // POST: Countries/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Code,Isocode2,Isocode3,DialCode,Nationality,CreatedBy]")] Country country)
        {
            if (ModelState.IsValid)
            {
                country.CreatedBy = Convert.ToInt32(HttpContext.Session.GetInt32("UserId"));

                _context.Add(country);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(country);
        }

        // GET: Countries/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if ((id == null) || (id == 0) )
            {
                return NotFound();
            }

            var country = await _context.Country.FindAsync(id);
            if (country == null)
            {
                return NotFound();
            }
            ViewData["CreatedBy"] = new SelectList(_context.UserMaster, "Id", "FirstName");
            ViewData["IsEditable"] = HttpContext.Session.GetInt32("IsEditable");
            return View(country);
        }

        // POST: Countries/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Code,Isocode2,Isocode3,DialCode,Nationality,CreatedBy")] Country country)
        {
            if (id != country.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    country.CreatedBy = Convert.ToInt32(HttpContext.Session.GetInt32("UserId"));
                    _context.Update(country);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CountryExists(country.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(country);
        }

        // GET: Countries/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var country = await _context.Country
                .FirstOrDefaultAsync(m => m.Id == id);
            if (country == null)
            {
                return NotFound();
            }

            return View(country);
        }

        // POST: Countries/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var country = await _context.Country.FindAsync(id);
            _context.Country.Remove(country);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CountryExists(int id)
        {
            return _context.Country.Any(e => e.Id == id);
        }
    }
}

Code/MasterDM/UI/VFS.UI.MasterDM/Views/Countries/Create.cshtml
@model VFS.Common.Models.Masters.Country

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

<h4>Country</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Code" class="control-label"></label>
                <input asp-for="Code" class="form-control" />
                <span asp-validation-for="Code" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Isocode2" class="control-label"></label>
                <input asp-for="Isocode2" class="form-control" />
                <span asp-validation-for="Isocode2" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Isocode3" class="control-label"></label>
                <input asp-for="Isocode3" class="form-control" />
                <span asp-validation-for="Isocode3" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DialCode" class="control-label"></label>
                <input asp-for="DialCode" class="form-control" />
                <span asp-validation-for="DialCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nationality" class="control-label"></label>
                <input asp-for="Nationality" class="form-control" />
                <span asp-validation-for="Nationality" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreatedBy" class="control-label"></label>
                @*<input asp-for="CreatedBy" class="form-control" />*@
                <select asp-for="CreatedBy" class="form-control" asp-items="ViewBag.CreatedBy"></select>
                <span asp-validation-for="CreatedBy" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Code/MasterDM/UI/VFS.UI.MasterDM/Views/Countries/Delete.cshtml
@model VFS.Common.Models.Masters.Country

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Country</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Code)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Code)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Isocode2)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Isocode2)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Isocode3)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Isocode3)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DialCode)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DialCode)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Nationality)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Nationality)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Code/MasterDM/UI/VFS.UI.MasterDM/Views/Countries/Details.cshtml
@model VFS.Common.Models.Masters.Country

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Country</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Code)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Code)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Isocode2)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Isocode2)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Isocode3)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Isocode3)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DialCode)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DialCode)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Nationality)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Nationality)
        </dd>
        @*<dt>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>*@
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Code/MasterDM/UI/VFS.UI.MasterDM/Views/Countries/Edit.cshtml
@model VFS.Common.Models.Masters.Country

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

<h4>Country</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>

                @if (ViewBag.IsEditable == 0)
                {
                    <input asp-for="Name" class="form-control" disabled />
                }
                else
                {
                    <input asp-for="Name" class="form-control" />
                }
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Code" class="control-label"></label>
                <input asp-for="Code" class="form-control" />
                <span asp-validation-for="Code" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Isocode2" class="control-label"></label>
                <input asp-for="Isocode2" class="form-control" />
                <span asp-validation-for="Isocode2" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Isocode3" class="control-label"></label>
                <input asp-for="Isocode3" class="form-control" />
                <span asp-validation-for="Isocode3" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DialCode" class="control-label"></label>
                <input asp-for="DialCode" class="form-control" />
                <span asp-validation-for="DialCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nationality" class="control-label"></label>
                <input asp-for="Nationality" class="form-control" />
                <span asp-validation-for="Nationality" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreatedBy" class="control-label"></label>
                <select asp-for="CreatedBy" class="form-control" asp-items="ViewBag.CreatedBy"></select>
                <span asp-validation-for="CreatedBy" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Code/MasterDM/UI/VFS.UI.MasterDM/Views/Countries/Index.cshtml
@model IEnumerable<VFS.Common.Models.Masters.Country>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <td>
                <label class="control-label">Search</label>
                <input class="form-control" id="Search"/> <input type="submit" value="Search" class="btn btn-group-lg" onclick="location.href='@Url.Action("Index", "Countries")?Search=' + document.getElementById('Search').value"/>
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Code)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Isocode2)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Isocode3)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DialCode)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nationality)
            </th>
            <th>
                CreatedBy
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Code)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Isocode2)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Isocode3)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DialCode)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nationality)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreatedByNavigation.FirstName)
                </td>
                <td>
                    @if (ViewBag.IsEditable == 1)
                    {
                        <a asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                    }
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>